[package]
name = "octez-evm-node-wasm-runtime"
version = "0.0.0-dev"
authors = [ "Etherlink Core Engineers <contact@tezos.com>" ]
edition = "2021"

[build-dependencies]
ocaml-build = { version = "1.*", features = ["dune"] }

[dependencies]
hex = "*"
ocaml = { version = "1.*" }
wasmer = { path = "../../src/rust_deps/wasmer-3.3.0/lib/api", default-features = false, features = ["cranelift", "jit"] }
wasmer-compiler-cranelift = { path = "../../src/rust_deps/wasmer-3.3.0/lib/compiler-cranelift" }
tezos_crypto_rs = { version = "0.6", default-features = false }
log = "0.4"
env_logger = "0.11"
