name: Build and Deploy Tezos Node

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2

    # - name: Free Disk Space (Ubuntu)
    #   uses: jlumbroso/free-disk-space@main
    #   with:
    #     # this might remove tools that are actually needed,
    #     # when set to "true" but frees about 6 GB
    #     tool-cache: true
        
    #     # all of these default to true, but feel free to set to
    #     # "false" if necessary for your workflow
    #     android: true
    #     dotnet: true
    #     haskell: true
    #     large-packages: true
    #     swap-storage: true

    # - name: Install OPAM
    #   run: |
    #     echo "/usr/local/bin" | sh <(curl -fsSL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh)
    # - name: Install Rust
    #   run: |
    #     cd $HOME
    #     wget https://sh.rustup.rs/rustup-init.sh
    #     chmod +x rustup-init.sh
    #     ./rustup-init.sh --profile minimal --default-toolchain 1.52.1 -y
    #     source $HOME/.cargo/env

    # - name: Install System Dependencies
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install -y \
    #       rsync \
    #       git \
    #       m4 \
    #       build-essential \
    #       patch \
    #       unzip \
    #       wget \
    #       pkg-config \
    #       libgmp-dev \
    #       libev-dev \
    #       libhidapi-dev \
    #       opam \
    #       jq \
    #       zlib1g-dev \
    #       bc \
    #       autoconf

    # - name: Initialize OPAM and Compile Sources
    #   run: |
    #     yes 1 | opam init --bare
    #     make build-deps
        

    # - name: Compile Sources
    #   run: |
    #      eval $(opam env)
    #      make

    # - name: Export PATH
    #   run: echo "$PWD/_build/install/default/bin/:$PATH" >> $GITHUB_PATH

    # - name: Check Installation
    #   run: octez-node --version

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Upload ZIP to S3
      uses: NotCoffee418/s3-zip-upload@v1.4
      env:
        AWS_SECRET_ID: ${{ secrets.AWS_SECRET_ID }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        AWS_REGION: us-east-1
        SOURCE_MODE: ZIP
        SOURCE_PATH: /home/runner/work/tezos-mirror/tezos-mirror
        DEST_FILE: tezos.zip

