name: Build and Deploy Tezos Node

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2

    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        # this might remove tools that are actually needed,
        # when set to "true" but frees about 6 GB
        tool-cache: false
        
        # all of these default to true, but feel free to set to
        # "false" if necessary for your workflow
        android: false
        dotnet: false
        haskell: false
        large-packages: false
        swap-storage: false

    - name: Install OPAM
      run: |
        echo "/usr/local/bin" | sh <(curl -fsSL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh)
    - name: Install Rust
      run: |
        cd $HOME
        wget https://sh.rustup.rs/rustup-init.sh
        chmod +x rustup-init.sh
        ./rustup-init.sh --profile minimal --default-toolchain 1.52.1 -y
        source $HOME/.cargo/env

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          rsync \
          git \
          m4 \
          build-essential \
          patch \
          unzip \
          wget \
          pkg-config \
          libgmp-dev \
          libev-dev \
          libhidapi-dev \
          opam \
          jq \
          zlib1g-dev \
          bc \
          autoconf

    - name: Initialize OPAM and Compile Sources
      run: |
        yes 1 | opam init --bare
        make build-deps
        

    - name: Compile Sources
      run: |
         eval $(opam env)
         make

    - name: Export PATH
      run: echo "$PWD/_build/install/default/bin/:$PATH" >> $GITHUB_PATH

    - name: Check Installation
      run: octez-node --version
